name: Our First Workflow
on:
  push:
    branches:
      - "feature/**"

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello, GitHub Actions!! Fxxk!!'
  pwd-ls:
    name: PWD & LS
    runs-on: ubuntu-latest
    steps:
      - name: Print working directory
        run: pwd
      - name: List files
        run: ls -al
